name: deploy mibo

on:
  workflow_dispatch:
  push:    
    # deactivated for now - has to be enabled by team
    branches-ignore:
      - '**'
    
     #paths: #branches: [ master ]
  
    #  - GameBot/**
    #  - .github/workflows/build-push-gamebot.yml
   
defaults:
  run:
    working-directory: GameBot
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
         
    # login to Azure
    - name: Login to Azure
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # build the docker image
    - name: build and push    
      run: |
        ls -a
        chmod +x ./teraform/deploy-team.sh
        sh ./teraform/deploy-team.sh mibo westeurope 5d9a229f-3bb4-46fb-9995-4d0625c98a34
